// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: chord/chord.proto

package chord

import (
	common "github.com/gedilabs/services/common"
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ChordNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node      *common.Node `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Successor *common.Node `protobuf:"bytes,2,opt,name=successor,proto3" json:"successor,omitempty"`
}

func (x *ChordNode) Reset() {
	*x = ChordNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chord_chord_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChordNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChordNode) ProtoMessage() {}

func (x *ChordNode) ProtoReflect() protoreflect.Message {
	mi := &file_chord_chord_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChordNode.ProtoReflect.Descriptor instead.
func (*ChordNode) Descriptor() ([]byte, []int) {
	return file_chord_chord_proto_rawDescGZIP(), []int{0}
}

func (x *ChordNode) GetNode() *common.Node {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *ChordNode) GetSuccessor() *common.Node {
	if x != nil {
		return x.Successor
	}
	return nil
}

type Finger struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node *common.Node `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Idx  uint64       `protobuf:"varint,2,opt,name=idx,proto3" json:"idx,omitempty"`
}

func (x *Finger) Reset() {
	*x = Finger{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chord_chord_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Finger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Finger) ProtoMessage() {}

func (x *Finger) ProtoReflect() protoreflect.Message {
	mi := &file_chord_chord_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Finger.ProtoReflect.Descriptor instead.
func (*Finger) Descriptor() ([]byte, []int) {
	return file_chord_chord_proto_rawDescGZIP(), []int{1}
}

func (x *Finger) GetNode() *common.Node {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *Finger) GetIdx() uint64 {
	if x != nil {
		return x.Idx
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nil bool `protobuf:"varint,1,opt,name=nil,proto3" json:"nil,omitempty"`
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chord_chord_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_chord_chord_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_chord_chord_proto_rawDescGZIP(), []int{2}
}

func (x *Empty) GetNil() bool {
	if x != nil {
		return x.Nil
	}
	return false
}

type Key struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Key) Reset() {
	*x = Key{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chord_chord_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Key) ProtoMessage() {}

func (x *Key) ProtoReflect() protoreflect.Message {
	mi := &file_chord_chord_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Key.ProtoReflect.Descriptor instead.
func (*Key) Descriptor() ([]byte, []int) {
	return file_chord_chord_proto_rawDescGZIP(), []int{3}
}

func (x *Key) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_chord_chord_proto protoreflect.FileDescriptor

var file_chord_chord_proto_rawDesc = []byte{
	0x0a, 0x11, 0x63, 0x68, 0x6f, 0x72, 0x64, 0x2f, 0x63, 0x68, 0x6f, 0x72, 0x64, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x63, 0x68, 0x6f, 0x72, 0x64, 0x1a, 0x13, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x59, 0x0a, 0x09, 0x43, 0x68, 0x6f, 0x72, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x20, 0x0a, 0x04,
	0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x2a,
	0x0a, 0x09, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52,
	0x09, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x22, 0x3c, 0x0a, 0x06, 0x46, 0x69,
	0x6e, 0x67, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4e, 0x6f, 0x64, 0x65,
	0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x78, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x03, 0x69, 0x64, 0x78, 0x22, 0x19, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03,
	0x6e, 0x69, 0x6c, 0x22, 0x15, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x32, 0xdb, 0x02, 0x0a, 0x05, 0x43,
	0x68, 0x6f, 0x72, 0x64, 0x12, 0x2b, 0x0a, 0x0d, 0x46, 0x69, 0x6e, 0x64, 0x53, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x6f, 0x72, 0x12, 0x0a, 0x2e, 0x63, 0x68, 0x6f, 0x72, 0x64, 0x2e, 0x4b, 0x65,
	0x79, 0x1a, 0x0c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x22,
	0x00, 0x12, 0x38, 0x0a, 0x16, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x73, 0x74, 0x50, 0x72, 0x65, 0x63,
	0x65, 0x64, 0x69, 0x6e, 0x67, 0x46, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x12, 0x0a, 0x2e, 0x63, 0x68,
	0x6f, 0x72, 0x64, 0x2e, 0x4b, 0x65, 0x79, 0x1a, 0x10, 0x2e, 0x63, 0x68, 0x6f, 0x72, 0x64, 0x2e,
	0x43, 0x68, 0x6f, 0x72, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x22, 0x00, 0x12, 0x2b, 0x0a, 0x0b, 0x50,
	0x72, 0x65, 0x64, 0x65, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x12, 0x0c, 0x2e, 0x63, 0x68, 0x6f,
	0x72, 0x64, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x22, 0x00, 0x12, 0x29, 0x0a, 0x09, 0x53, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x6f, 0x72, 0x12, 0x0c, 0x2e, 0x63, 0x68, 0x6f, 0x72, 0x64, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x1a, 0x0c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4e, 0x6f, 0x64,
	0x65, 0x22, 0x00, 0x12, 0x33, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x65,
	0x64, 0x65, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x12, 0x0c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x1a, 0x0e, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x46, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x0d, 0x2e,
	0x63, 0x68, 0x6f, 0x72, 0x64, 0x2e, 0x46, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x1a, 0x0e, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x12, 0x28,
	0x0a, 0x06, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x0c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x1a, 0x0e, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x65, 0x64, 0x69, 0x6c, 0x61, 0x62, 0x73, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x63, 0x68, 0x6f, 0x72, 0x64, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_chord_chord_proto_rawDescOnce sync.Once
	file_chord_chord_proto_rawDescData = file_chord_chord_proto_rawDesc
)

func file_chord_chord_proto_rawDescGZIP() []byte {
	file_chord_chord_proto_rawDescOnce.Do(func() {
		file_chord_chord_proto_rawDescData = protoimpl.X.CompressGZIP(file_chord_chord_proto_rawDescData)
	})
	return file_chord_chord_proto_rawDescData
}

var file_chord_chord_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_chord_chord_proto_goTypes = []interface{}{
	(*ChordNode)(nil),     // 0: chord.ChordNode
	(*Finger)(nil),        // 1: chord.Finger
	(*Empty)(nil),         // 2: chord.Empty
	(*Key)(nil),           // 3: chord.Key
	(*common.Node)(nil),   // 4: common.Node
	(*common.Status)(nil), // 5: common.Status
}
var file_chord_chord_proto_depIdxs = []int32{
	4,  // 0: chord.ChordNode.node:type_name -> common.Node
	4,  // 1: chord.ChordNode.successor:type_name -> common.Node
	4,  // 2: chord.Finger.node:type_name -> common.Node
	3,  // 3: chord.Chord.FindSuccessor:input_type -> chord.Key
	3,  // 4: chord.Chord.ClosestPrecedingFinger:input_type -> chord.Key
	2,  // 5: chord.Chord.Predecessor:input_type -> chord.Empty
	2,  // 6: chord.Chord.Successor:input_type -> chord.Empty
	4,  // 7: chord.Chord.UpdatePredecessor:input_type -> common.Node
	1,  // 8: chord.Chord.UpdateFingerTable:input_type -> chord.Finger
	4,  // 9: chord.Chord.Notify:input_type -> common.Node
	4,  // 10: chord.Chord.FindSuccessor:output_type -> common.Node
	0,  // 11: chord.Chord.ClosestPrecedingFinger:output_type -> chord.ChordNode
	4,  // 12: chord.Chord.Predecessor:output_type -> common.Node
	4,  // 13: chord.Chord.Successor:output_type -> common.Node
	5,  // 14: chord.Chord.UpdatePredecessor:output_type -> common.Status
	5,  // 15: chord.Chord.UpdateFingerTable:output_type -> common.Status
	5,  // 16: chord.Chord.Notify:output_type -> common.Status
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_chord_chord_proto_init() }
func file_chord_chord_proto_init() {
	if File_chord_chord_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_chord_chord_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChordNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chord_chord_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Finger); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chord_chord_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chord_chord_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Key); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chord_chord_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chord_chord_proto_goTypes,
		DependencyIndexes: file_chord_chord_proto_depIdxs,
		MessageInfos:      file_chord_chord_proto_msgTypes,
	}.Build()
	File_chord_chord_proto = out.File
	file_chord_chord_proto_rawDesc = nil
	file_chord_chord_proto_goTypes = nil
	file_chord_chord_proto_depIdxs = nil
}
